- hosts: all
  become: yes
  tasks:
  
  # - name: disable firewall service for labs
  #   service:
  #      name: firewalld
  #      state: stopped
  #      enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent
 
   - name: install updates
     yum: update_cache=yes
     when: ansible_os_family == "RedHat"
     
   - name: Add docker repository
     get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
   
   - name: Install supported version of docker
     ansible.builtin.package:
      name: [docker-ce]
      state: present

   - name: Create other directories required
     ansible.builtin.file:
      path: "{{ item }}"
      state: directory
     with_items:
      - /etc/docker
      - /etc/systemd/system/docker.service.d
    
   - name: Set cgroup driver as systemd
     ansible.builtin.template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json

   - name: Start and enable docker service
     ansible.builtin.systemd:
       name: docker
       state: started
       enabled: yes
       daemon_reload: yes

   - name: Setup Docker Proxy
     ansible.builtin.template:
       src: docker-proxy.j2
       dest: /etc/systemd/system/docker.service.d/http-proxy.conf
     when: setup_proxy

   - name: Restart docker service
     ansible.builtin.systemd:
      name: docker
      state: restarted
      daemon_reload: yes
   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.14.0
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: masters
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.14.0
        state: present
        allow_downgrade: yes

- hosts: all
  become: yes
  tasks:
   - name: reboot ALL machines
     reboot:
